//! Paper artifacts (D-78): LaTeX tables under `paper/tables/` and vector
//! figures under `paper/figures/`. Nothing in them is typed by hand (SPEC
//! §0 rule 7).
//!
//! - **Measured tables** (the §1 verdicts, Q2's break-even, the claims, the
//!   primitives) come from the verified M9 archives through [`Doc`], the
//!   same data and statistics as `BENCHMARKS.md`. The claims table is
//!   `BENCHMARKS.md`'s own §5 table, converted.
//! - **The security suite** (SPEC §11.2) is read from `tests/security.rs`
//!   and `tests/concurrency.rs`: each test's assertions, in order. The
//!   suite is then run, and each row records whether its test passed. An
//!   assertion this module cannot classify stops generation.
//! - **The M4 oracle** comes from `docs/test-reports/policy-oracle-m4.json`.
//! - **Figures** are drawn by `scripts/paper_figures.py` from
//!   `results/summary.json`, which [`Doc::load`] has just regenerated.
//!
//! Each table is a bare `tabular` (the security suite a `longtable`), for
//! the author to wrap in a float with a caption. They need `booktabs` and
//! `array`, and the security table also `longtable`.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use std::process::Command;

use serde_json::Value;

use crate::benchmarks::{Doc, POSITIONING_CAPTION, Revision, cells};
use crate::report::us;

/// LaTeX for a cell of `BENCHMARKS.md`: `**bold**` and `` `code` `` become
/// `\textbf` and `\texttt`, and every special character is escaped. A
/// character with no mapping here is an error, so nothing is dropped
/// silently.
pub fn tex(s: &str) -> Result<String, String> {
    let mut out = String::with_capacity(s.len() + 16);
    let (mut bold, mut code, mut quoted) = (false, false, false);
    let mut it = s.chars().peekable();
    while let Some(c) = it.next() {
        if c == '*' && it.peek() == Some(&'*') && !code {
            it.next();
            out.push_str(if bold { "}" } else { "\\textbf{" });
            bold = !bold;
            continue;
        }
        if c == '`' {
            out.push_str(if code { "}" } else { "\\texttt{" });
            code = !code;
            continue;
        }
        if c == '"' {
            out.push_str(if quoted { "''" } else { "``" });
            quoted = !quoted;
            continue;
        }
        out.push_str(&match c {
            '\\' => "\\textbackslash{}".into(),
            '<' => "$<$".into(),
            '>' => "$>$".into(),
            '|' => "$|$".into(),
            '&' => "\\&".into(),
            '%' => "\\%".into(),
            '$' => "\\$".into(),
            '#' => "\\#".into(),
            '_' => "\\_".into(),
            '{' => "\\{".into(),
            '}' => "\\}".into(),
            '~' => "\\textasciitilde{}".into(),
            '^' => "\\textasciicircum{}".into(),
            '×' => "$\\times$".into(),
            '–' => "--".into(),
            '—' => "---".into(),
            'µ' => "\\textmu{}".into(),
            '≈' => "$\\approx$".into(),
            '≥' => "$\\geq$".into(),
            '≤' => "$\\leq$".into(),
            '≠' => "$\\neq$".into(),
            '²' => "\\textsuperscript{2}".into(),
            'α' => "$\\alpha$".into(),
            'β' => "$\\beta$".into(),
            'σ' => "$\\sigma$".into(),
            '±' => "$\\pm$".into(),
            '→' => "$\\rightarrow$".into(),
            '−' => "$-$".into(),
            '§' => "\\S{}".into(),
            '†' => "\\dag{}".into(),
            '’' => "'".into(),
            '“' => "``".into(),
            '”' => "''".into(),
            c if c.is_ascii() => c.to_string(),
            c => return Err(format!("no LaTeX mapping for {c:?} in {s:?}")),
        });
    }
    if bold || code || quoted {
        return Err(format!("unbalanced markup in {s:?}"));
    }
    Ok(out)
}

const HEADER: &str = "% Generated by `dc-bench paper` (crates/dc-bench/src/paper.rs). Do not edit:\n% regenerate it (ARTIFACT.md). Needs booktabs and array (security.tex also longtable).\n";

fn short(v: &str) -> Result<&'static str, String> {
    Ok(match v {
        "net benefit" => "+",
        "not a net benefit" => "$-$",
        "no material difference" => "$=$",
        "inconclusive" => "?",
        "inconclusive (runs disagree)" => "?r",
        _ => return Err(format!("unknown verdict {v}")),
    })
}

/// The §1 verdict table: B/D (warm+prefix), A/C and A/C-batch (warm), each
/// ratio with its 95% CI and its verdict under the frozen rule.
fn verdicts(doc: &Doc) -> Result<String, String> {
    let mut w = String::from(HEADER);
    w.push_str("% The frozen plan's §1 verdict table: median ratio [95% CI] and verdict per cell.\n% Verdicts (frozen plan §6): + net benefit (CI below 0.90); $-$ not a net benefit (CI above 1.10);\n% $=$ no material difference; ? inconclusive; ?r inconclusive because the three runs disagree.\n");
    w.push_str("\\begin{tabular}{lrr@{\\,}cr@{\\,}cr@{\\,}c}\n\\toprule\n");
    w.push_str("Profile & $N$ & \\multicolumn{2}{c}{B/D, warm+prefix} & \\multicolumn{2}{c}{A/C, warm} & \\multicolumn{2}{c}{A/C-batch, warm} \\\\\n\\midrule\n");
    let mut order = cells();
    let rank = |p: &str| {
        ["small", "medium", "large", "medium-approval"]
            .iter()
            .position(|x| *x == p)
    };
    order.sort_by_key(|&(n, p)| (rank(p), n));
    let mut last = "";
    for (n, profile) in order {
        if !last.is_empty() && last != profile {
            w.push_str("\\midrule\n");
        }
        last = profile;
        let mut row = format!("{} & {n}", tex(profile)?);
        for k in ["bd", "ac", "acb"] {
            let (r, _, v) = doc.verdict(k, n, profile)?;
            let _ = write!(
                row,
                " & {:.2} [{:.2}, {:.2}] & {}",
                r.value,
                r.ci.0,
                r.ci.1,
                short(v)?
            );
        }
        let _ = writeln!(w, "{row} \\\\");
    }
    w.push_str("\\bottomrule\n\\end{tabular}\n");
    Ok(w)
}

/// Q2: the break-even N per profile, with the size difference at N = 1 and
/// A's saving over C at N = 10.
fn breakeven(doc: &Doc) -> Result<String, String> {
    let mut w = String::from(HEADER);
    w.push_str("% Q2: chain bytes, A against C. Break-even is the first N in 1-10 at which A's and C's sizes change order.\n");
    w.push_str("\\begin{tabular}{lrrr}\n\\toprule\n");
    w.push_str("Profile & Break-even $N$ & A $-$ C at $N = 1$ (bytes) & A smaller than C at $N = 10$ \\\\\n\\midrule\n");
    for profile in ["small", "medium", "large", "medium-approval"] {
        let be = doc
            .break_even(profile)?
            .map_or("none in 1--10".to_owned(), |n| n.to_string());
        let d1 = doc.total("A", 1, profile)? - doc.total("C", 1, profile)?;
        let s10 = 100.0 * (1.0 - doc.total("A", 10, profile)? / doc.total("C", 10, profile)?);
        let _ = writeln!(w, "{} & {be} & {d1:+.0} & {s10:.1}\\% \\\\", tex(profile)?);
    }
    w.push_str("\\bottomrule\n\\end{tabular}\n");
    Ok(w)
}

/// The claims table: `BENCHMARKS.md`'s §5 table, rendered from the same
/// template and converted.
fn claims(doc: &Doc, template: &Path) -> Result<String, String> {
    let md = doc.fill_for(
        &fs::read_to_string(template).map_err(|e| format!("{}: {e}", template.display()))?,
        Revision::Current,
    )?;
    let start = md
        .find("\n## 5. Paper claims checked")
        .ok_or("BENCHMARKS template has no §5 claims table")?;
    let rows: Vec<Vec<String>> = md[start..]
        .lines()
        .skip_while(|l| !l.starts_with('|'))
        .take_while(|l| l.starts_with('|'))
        .skip(2)
        .map(|l| {
            l.trim()
                .trim_matches('|')
                .split(" | ")
                .map(|c| c.trim().to_owned())
                .collect()
        })
        .collect();
    let mut w = String::from(HEADER);
    w.push_str(
        "% The paper claims checked against revision 2026-09-29 (SPEC §13.11): BENCHMARKS.md §5.\n",
    );
    w.push_str(
        "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{0.27\\linewidth}l>{\\raggedright\\arraybackslash}p{0.11\\linewidth}>{\\raggedright\\arraybackslash}p{0.42\\linewidth}}\n\\toprule\n",
    );
    w.push_str("Claim & Paper & Verdict & Evidence \\\\\n\\midrule\n");
    for (i, r) in rows.iter().enumerate() {
        if r.len() != 4 {
            return Err(format!("claims row {} has {} cells", i + 1, r.len()));
        }
        let cells: Vec<String> = r.iter().map(|c| tex(c)).collect::<Result<_, _>>()?;
        let _ = writeln!(w, "{} \\\\", cells.join(" & "));
        if i + 1 < rows.len() {
            w.push_str("\\addlinespace\n");
        }
    }
    w.push_str("\\bottomrule\n\\end{tabular}\n");
    Ok(w)
}

/// Microseconds for the primitives table: like the report's, with three
/// decimals below one microsecond.
fn prim_us(ns: f64) -> String {
    if ns < 1000.0 {
        format!("{:.3}", ns / 1000.0)
    } else {
        us(ns)
    }
}

/// Primitive costs: criterion medians and their 95% CIs (D-73).
fn primitives(doc: &Doc) -> Result<String, String> {
    let get = |id: &str| -> Result<(f64, (f64, f64)), String> {
        doc.criterion
            .iter()
            .find(|c| c.0 == id)
            .map(|c| (c.1, c.2))
            .ok_or_else(|| format!("no criterion estimate {id}"))
    };
    let mut w = String::from(HEADER);
    w.push_str(
        "% Primitive costs on this machine: criterion medians, 95% CIs, microseconds (D-73).\n",
    );
    w.push_str("\\begin{tabular}{lrr}\n\\toprule\n");
    w.push_str("Operation & Median (\\textmu{}s) & 95\\% CI (\\textmu{}s) \\\\\n\\midrule\n");
    let line = |w: &mut String, label: &str, id: &str| -> Result<(), String> {
        let (m, ci) = get(id)?;
        let _ = writeln!(
            w,
            "{} & {} & [{}, {}] \\\\",
            tex(label)?,
            prim_us(m),
            prim_us(ci.0),
            prim_us(ci.1)
        );
        Ok(())
    };
    w.push_str("\\multicolumn{3}{l}{\\emph{BLS12-381 (blst)}} \\\\\n");
    line(&mut w, "verify (one signature)", "bls/verify")?;
    for n in 2..=11 {
        line(
            &mut w,
            &format!("`aggregate_verify`, {n} messages"),
            &format!("bls/aggregate_verify/{n}"),
        )?;
    }
    line(&mut w, "Miller loop", "bls/miller_loop")?;
    line(&mut w, "final exponentiation", "bls/final_exp")?;
    line(
        &mut w,
        "hash-to-G2 proxy: context + `aggregate`",
        "bls/hash_to_g2_proxy",
    )?;
    line(&mut w, "pairing context alone", "bls/pairing_context")?;
    let h = get("bls/hash_to_g2_proxy")?.0 - get("bls/pairing_context")?.0;
    let _ = writeln!(
        w,
        "{} & {} & --- \\\\",
        tex("hash to G2, estimated (proxy − context)")?,
        prim_us(h)
    );
    w.push_str("\\midrule\n\\multicolumn{3}{l}{\\emph{Ed25519 (ed25519-dalek)}} \\\\\n");
    line(
        &mut w,
        "`verify_strict` (one signature)",
        "ed25519/verify_strict",
    )?;
    for n in 2..=11 {
        line(
            &mut w,
            &format!("`verify_batch`, {n} signatures"),
            &format!("ed25519/verify_batch/{n}"),
        )?;
    }
    w.push_str("\\bottomrule\n\\end{tabular}\n");
    Ok(w)
}

/// Exploratory: C (warm) and D (warm+prefix) against arm E, medium, at
/// matching depth. Its caption, which lists E's functional gaps, is
/// `\\tabcapPositioning` in `paper/tables/captions.tex`.
fn positioning(doc: &Doc) -> Result<String, String> {
    let mut w = String::from(HEADER);
    w.push_str("% EXPLORATORY (not pre-registered): BENCHMARKS.md §8. Caption: \\tabcapPositioning (paper/tables/captions.tex).\n");
    w.push_str("\\begin{tabular}{lrrrrrr}\n\\toprule\n");
    w.push_str("$N$ (Biscuit depth) & C, warm (\\textmu{}s) & D, warm+prefix (\\textmu{}s) & E (\\textmu{}s) & AIP's code here (\\textmu{}s; exploratory) & C $\\div$ E & D $\\div$ E \\\\\n\\midrule\n");
    for r in doc.positioning()? {
        let _ = writeln!(
            w,
            "{} ({}) & {} & {} & {} & {} & {:.2} & {:.2} \\\\",
            r.n,
            r.n - 1,
            us(r.c),
            us(r.d),
            us(r.e),
            r.aip.map_or("---".into(), us),
            r.c / r.e,
            r.d / r.e
        );
    }
    w.push_str("\\bottomrule\n\\end{tabular}\n");
    Ok(w)
}

/// Caption macros for the tables that need one (`paper/tables/captions.tex`;
/// the figures' are in `paper/figures/captions.tex`, from
/// `scripts/paper_figures.py`).
fn captions() -> Result<String, String> {
    let mut w = String::from(HEADER);
    let _ = writeln!(
        w,
        "\\newcommand{{\\tabcapPositioning}}{{{}}}",
        tex(POSITIONING_CAPTION)?
    );
    Ok(w)
}

// ---- the security suite ----

/// Which instantiation a test or an assertion is compiled for (D-84).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Inst {
    Both,
    Default,
    Aggregate,
}

/// The instantiation a `#[cfg]` line selects, if it is one of the suite's.
fn cfg_of(line: &str) -> Option<Inst> {
    match line.trim() {
        "#[cfg(feature = \"aggregate-variant\")]" => Some(Inst::Aggregate),
        "#[cfg(not(feature = \"aggregate-variant\"))]" => Some(Inst::Default),
        _ => None,
    }
}

/// The argument text of each `assert!`, `assert_eq!` or `assert_ne!` in
/// `body`, whitespace-collapsed, in order, with the instantiation a `#[cfg]`
/// on the line before it selects. String literals are skipped when matching
/// parentheses.
fn assertions(body: &str) -> Vec<(String, Inst)> {
    let b = body.as_bytes();
    let mut out = vec![];
    let mut i = 0;
    while let Some(off) = body[i..].find("assert") {
        let at = i + off;
        let rest = &body[at..];
        let open = ["assert!(", "assert_eq!(", "assert_ne!("]
            .iter()
            .find(|m| rest.starts_with(**m))
            .map(|m| at + m.len());
        let Some(start) = open else {
            i = at + 6;
            continue;
        };
        let (mut depth, mut k, mut instr) = (1, start, false);
        while k < b.len() && depth > 0 {
            let c = b[k];
            if instr {
                if c == b'\\' {
                    k += 1;
                } else if c == b'"' {
                    instr = false;
                }
            } else if c == b'"' {
                instr = true;
            } else if c == b'(' {
                depth += 1;
            } else if c == b')' {
                depth -= 1;
            }
            k += 1;
        }
        let line_start = body[..at].rfind('\n').unwrap_or(0);
        let prev_start = body[..line_start].rfind('\n').map_or(0, |x| x + 1);
        let inst = cfg_of(&body[prev_start..line_start]).unwrap_or(Inst::Both);
        out.push((
            body[start..k - 1]
                .split_whitespace()
                .collect::<Vec<_>>()
                .join(" "),
            inst,
        ));
        i = k;
    }
    out
}

fn counter(field: &str) -> Option<&'static str> {
    Some(match field.trim().trim_start_matches("n.") {
        "pairings()" => "pairings",
        "resolver_calls" => "resolver calls",
        "policy_store_calls" => "policy-store calls",
        "sig_verifications" => "signature checks",
        "hash_to_curve" => "hash-to-G2",
        "miller_loops" => "Miller loops",
        "final_exps" => "final exps",
        _ => return None,
    })
}

/// What one assertion asserts, in the table's words.
fn classify(a: &str) -> Result<String, String> {
    if let Some(i) = a.find("RegistryError::") {
        let name: String = a[i + 15..]
            .chars()
            .take_while(|c| c.is_ascii_alphanumeric())
            .collect();
        return Ok(format!("registry rejects ({name})"));
    }
    if let Some(i) = a.find("Reject::L") {
        let line: String = a[i + 9..]
            .chars()
            .take_while(|c| c.is_ascii_digit())
            .collect();
        return Ok(format!("L{line}"));
    }
    if a.contains("Ok(Decision::AllowWithApproval") {
        return Ok("accept (with approval)".into());
    }
    if a.starts_with("run(") && a.ends_with("Ok(())") {
        return Ok("phase 8 accepts the unmutated chain".into());
    }
    if a.ends_with(".is_ok()") {
        return Ok("accept".into());
    }
    // Operation counts: (n.a, n.b, …), (x, y, …)
    if let Some(rest) = a.strip_prefix('(')
        && let Some((fields, values)) = rest.split_once("), (")
    {
        let values = values.split(')').next().unwrap_or("");
        let f: Vec<&str> = fields
            .split(',')
            .map(str::trim)
            .filter(|x| !x.is_empty())
            .collect();
        let v: Vec<&str> = values.split(',').map(str::trim).collect();
        if f.len() == v.len() && f.iter().all(|x| counter(x).is_some()) {
            return Ok(f
                .iter()
                .zip(&v)
                .map(|(f, v)| format!("{} {v}", counter(f).expect("checked")))
                .collect::<Vec<_>>()
                .join(", "));
        }
    }
    Ok(match a {
        "n.resolver_calls > 0 && n.policy_store_calls > 0" => {
            "cold: resolver and policy-store calls > 0".into()
        }
        "other.load(Relaxed), 0" => "no outcome other than accept, L17, L50".into(),
        a if a.starts_with("per_round.iter().all(|a| *a == 1)") => {
            "exactly 1 accept per round".into()
        }
        "l17.load(Relaxed) + l50.load(Relaxed), ((THREADS - 1) * rounds) as u64" => {
            "every other attempt L17 or L50".into()
        }
        _ => return Err(format!("unclassified assertion: {a}")),
    })
}

/// "L02, L02, L05" → "L02 (×2); L05".
fn compress(v: &[String]) -> String {
    let mut out: Vec<(String, usize)> = vec![];
    for x in v {
        match out.last_mut() {
            Some((y, k)) if y == x => *k += 1,
            _ => out.push((x.clone(), 1)),
        }
    }
    out.into_iter()
        .map(|(x, k)| if k > 1 { format!("{x} (×{k})") } else { x })
        .collect::<Vec<_>>()
        .join("; ")
}

/// One test: its section, name, the instantiations it is compiled for, and
/// its asserted outcomes.
struct TestRow {
    section: String,
    name: String,
    inst: Inst,
    asserted: String,
}

/// Every `#[test]` in `src`, in file order. Sections are the
/// `// ====…==== title` lines; a `#[cfg]` just before `#[test]` limits the
/// test to one instantiation.
fn tests_of(src: &str, default_section: &str) -> Result<Vec<TestRow>, String> {
    let mut out = vec![];
    let mut section = default_section.to_owned();
    let lines: Vec<&str> = src.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let l = lines[i];
        if let Some(t) = l.strip_prefix("// ====") {
            section = t.trim_start_matches('=').trim().to_owned();
        }
        if l.trim() == "#[test]" {
            let sig = lines.get(i + 1).copied().unwrap_or("");
            let name = sig
                .trim()
                .strip_prefix("fn ")
                .and_then(|s| s.split('(').next())
                .ok_or_else(|| format!("no fn after #[test] at line {}", i + 1))?
                .to_owned();
            // The body runs to the next top-level closing brace.
            let mut j = i + 2;
            while j < lines.len() && lines[j] != "}" {
                j += 1;
            }
            let body = lines[i + 1..=j.min(lines.len() - 1)].join("\n");
            let asserted: Vec<String> = assertions(&body)
                .iter()
                .map(|(a, inst)| {
                    let c = classify(a).map_err(|e| format!("{name}: {e}"))?;
                    Ok(match inst {
                        Inst::Both => c,
                        Inst::Default => format!("default: {c}"),
                        Inst::Aggregate => format!("aggregate variant: {c}"),
                    })
                })
                .collect::<Result<_, String>>()?;
            if asserted.is_empty() {
                return Err(format!("{name}: no assertion found"));
            }
            let inst = i
                .checked_sub(1)
                .and_then(|k| cfg_of(lines[k]))
                .unwrap_or(Inst::Both);
            out.push(TestRow {
                section: section.clone(),
                name,
                inst,
                asserted: compress(&asserted),
            });
            i = j;
        }
        i += 1;
    }
    Ok(out)
}

/// Runs the two suites in release mode, for the default instantiation or,
/// with `aggregate`, the aggregate variant, and returns each test's result.
fn run_suites(root: &Path, aggregate: bool) -> Result<BTreeMap<String, bool>, String> {
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".into());
    let mut cmd = Command::new(cargo);
    cmd.current_dir(root).args([
        "test",
        "--release",
        "-p",
        "delegationchain",
        "--test",
        "security",
        "--test",
        "concurrency",
    ]);
    if aggregate {
        cmd.args(["--features", "aggregate-variant"]);
    }
    let out = cmd.output().map_err(|e| format!("cargo test: {e}"))?;
    let text = String::from_utf8_lossy(&out.stdout);
    let mut m = BTreeMap::new();
    for l in text.lines() {
        if let Some(rest) = l.strip_prefix("test ")
            && let Some((name, res)) = rest.rsplit_once(" ... ")
        {
            m.insert(name.trim().to_owned(), res.trim() == "ok");
        }
    }
    if m.is_empty() {
        return Err(format!(
            "cargo test printed no results:\n{}",
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    Ok(m)
}

/// The security suite as threat → asserted line (SPEC §11.2), for both
/// instantiations (D-84).
fn security(root: &Path) -> Result<String, String> {
    let read = |p: &str| fs::read_to_string(root.join(p)).map_err(|e| format!("{p}: {e}"));
    let mut rows = tests_of(&read("tests/security.rs")?, "security")?;
    rows.extend(tests_of(
        &read("tests/concurrency.rs")?,
        "T3b replay, concurrent (Theorem 5)",
    )?);
    let runs = [run_suites(root, false)?, run_suites(root, true)?];
    let mut w = String::from(HEADER);
    w.push_str("% The security suite (SPEC §11.2): each test's assertions in order, from tests/security.rs and\n% tests/concurrency.rs. Ln is the Algorithm line whose Reject variant the test asserts.\n% The last two columns are the results of running the suites when this file was generated, for the\n% default instantiation (Ed25519 per hop) and the aggregate variant (BLS); --- marks a test compiled\n% for the other instantiation only (D-84).\n");
    w.push_str(
        "\\begin{longtable}{>{\\raggedright\\arraybackslash}p{0.33\\linewidth}>{\\raggedright\\arraybackslash}p{0.42\\linewidth}ll}\n\\toprule\n",
    );
    w.push_str(
        "Test & Asserted, in order & Default & Aggregate \\\\\n\\midrule\n\\endhead\n\\bottomrule\n\\endfoot\n",
    );
    let mut section = String::new();
    let mut passed = [0usize; 2];
    let mut total = [0usize; 2];
    for r in &rows {
        if r.section != section {
            if !section.is_empty() {
                w.push_str("\\midrule\n");
            }
            let _ = writeln!(
                w,
                "\\multicolumn{{4}}{{l}}{{\\emph{{{}}}}} \\\\",
                tex(&r.section)?
            );
            section = r.section.clone();
        }
        let mut cells = vec![];
        for (k, inst) in [Inst::Default, Inst::Aggregate].iter().enumerate() {
            if r.inst != Inst::Both && r.inst != *inst {
                cells.push("---".to_owned());
                continue;
            }
            let ok = *runs[k]
                .get(r.name.as_str())
                .ok_or_else(|| format!("{} did not run ({inst:?})", r.name))?;
            total[k] += 1;
            passed[k] += usize::from(ok);
            cells.push(if ok {
                "yes".into()
            } else {
                "\\textbf{no}".into()
            });
        }
        let _ = writeln!(
            w,
            "\\texttt{{{}}} & {} & {} \\\\",
            // Long test names may break after an underscore.
            tex(&r.name)?.replace("\\_", "\\_\\allowbreak{}"),
            tex(&r.asserted)?,
            cells.join(" & ")
        );
    }
    w.push_str("\\end{longtable}\n");
    let _ = writeln!(
        w,
        "% Default: {} of {} tests passed. Aggregate variant: {} of {} tests passed.",
        passed[0], total[0], passed[1], total[1]
    );
    Ok(w)
}

// ---- the M4 oracle ----

fn oracle(root: &Path) -> Result<String, String> {
    let p = root.join("docs/test-reports/policy-oracle-m4.json");
    let v: Value =
        serde_json::from_str(&fs::read_to_string(&p).map_err(|e| format!("{}: {e}", p.display()))?)
            .map_err(|e| e.to_string())?;
    let n = |v: &Value| -> Result<u64, String> {
        v.as_u64().ok_or_else(|| format!("not a count: {v}"))
    };
    let frac = |v: &Value| -> String { v.as_f64().map_or("---".into(), |x| format!("{x:.4}")) };
    let thousands = |x: u64| -> String {
        let s = x.to_string();
        let mut out = String::new();
        for (i, c) in s.chars().enumerate() {
            if i > 0 && (s.len() - i).is_multiple_of(3) {
                out.push(',');
            }
            out.push(c);
        }
        out
    };
    let c = &v["contains"];
    let mut w = String::from(HEADER);
    let _ = writeln!(
        w,
        "% The M4 differential oracle (SPEC §9.7; seed {}): test statistics, not benchmark results.\n% Soundness: the procedure never answers true where the enumerating oracle answers false.\n% Completeness: the share of the oracle's true answers that the procedure also finds.",
        v["seed"]
    );
    w.push_str("\\begin{tabular}{llrrrr}\n\\toprule\n");
    w.push_str("Procedure & Inputs & Cases & Soundness violations & Oracle true & Completeness \\\\\n\\midrule\n");
    let _ = writeln!(
        w,
        "Contains & all well-formed pairs & {} & {} & {} & {} \\\\",
        thousands(n(&c["wellformed_pairs"])?),
        n(&c["soundness_violations"])?,
        thousands(n(&c["completeness_overall"]["oracle_true"])?),
        frac(&c["completeness_overall"]["completeness"])
    );
    let _ = writeln!(
        w,
        " & no child rule unsatisfiable & & & {} & {} \\\\",
        thousands(n(
            &c["completeness_when_no_child_rule_is_unsatisfiable"]["oracle_true"]
        )?),
        frac(&c["completeness_when_no_child_rule_is_unsatisfiable"]["completeness"])
    );
    if let Some(m) = c["completeness_by_category"].as_object() {
        for (cat, x) in m {
            let _ = writeln!(
                w,
                " & {} & & & {} & {} \\\\",
                tex(cat)?,
                thousands(n(&x["oracle_true"])?),
                frac(&x["completeness"])
            );
        }
    }
    let _ = writeln!(
        w,
        "\\midrule\n\\multicolumn{{6}}{{l}}{{\\emph{{Contains reflexivity: {} checks, {} failures; malformed scopes rejected: {}}}}} \\\\",
        thousands(n(&c["reflexivity_checks"])?),
        n(&c["reflexivity_failures"])?,
        thousands(n(&c["malformed_scopes_rejected"])?)
    );
    w.push_str("\\midrule\n");
    if let Some(m) = v["implies_unsat_by_type"].as_object() {
        for which in ["implies", "unsat"] {
            for (ty, x) in m {
                let _ = writeln!(
                    w,
                    "{} & {} & {} & {} & {} & {} \\\\",
                    if which == "implies" {
                        "Implies"
                    } else {
                        "Unsat"
                    },
                    tex(ty)?,
                    thousands(n(&x["cases"])?),
                    n(&x["soundness_violations"])?,
                    thousands(n(&x[which]["oracle_true"])?),
                    frac(&x[which]["completeness"])
                );
            }
        }
    }
    w.push_str("\\bottomrule\n\\end{tabular}\n");
    Ok(w)
}

/// Writes every table into `out/tables/` and every figure into
/// `out/figures/`.
pub fn render(
    results: &Path,
    criterion: &Path,
    root: &Path,
    out: &Path,
    threads: usize,
) -> Result<(), String> {
    let doc = Doc::load(results, criterion, threads)?;
    // The claims table cites the paper in docs/; its section map must be for
    // that file (D-86).
    let pdf = fs::read(root.join("docs/paper.pdf")).map_err(|e| format!("docs/paper.pdf: {e}"))?;
    let have = crate::report::hex(&dc_types::digest::sha256(&[&pdf]));
    let want = doc
        .sections
        .as_ref()
        .and_then(|m| m["current"]["sha256"].as_str())
        .ok_or("docs/paper-sections.json has no current.sha256")?;
    if have != want {
        return Err(format!(
            "docs/paper-sections.json is for another paper (current.sha256 {want}, docs/paper.pdf {have}): update it from the new paper (D-86)"
        ));
    }
    let tables = out.join("tables");
    fs::create_dir_all(&tables).map_err(|e| e.to_string())?;
    let template = root.join("crates/dc-bench/BENCHMARKS.template.md");
    for (name, body) in [
        ("verdicts.tex", verdicts(&doc)?),
        ("breakeven.tex", breakeven(&doc)?),
        ("claims.tex", claims(&doc, &template)?),
        ("primitives.tex", primitives(&doc)?),
        ("positioning.tex", positioning(&doc)?),
        ("captions.tex", captions()?),
        ("oracle.tex", oracle(root)?),
        ("security.tex", security(root)?),
    ] {
        fs::write(tables.join(name), body).map_err(|e| e.to_string())?;
        eprintln!("paper: tables/{name}");
    }
    let st = Command::new("bash")
        .arg(root.join("scripts/paper_figures.sh"))
        .arg(results)
        .arg(out.join("figures"))
        .status()
        .map_err(|e| format!("figures: {e}"))?;
    if !st.success() {
        return Err(format!("figures failed: {st}"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn markup_and_specials_are_escaped() {
        assert_eq!(
            tex("**Not supported** in `tests/a_b.rs`: 5% × 2 µs").unwrap(),
            "\\textbf{Not supported} in \\texttt{tests/a\\_b.rs}: 5\\% $\\times$ 2 \\textmu{}s"
        );
        assert_eq!(tex("\"a\" > b").unwrap(), "``a'' $>$ b");
        assert!(tex("ж").is_err());
        assert!(tex("**open").is_err());
    }

    #[test]
    fn assertions_are_classified() {
        let body = r#"
            assert_eq!(v.verify(&x), Err(Reject::L23Unresolvable { k: 2 }));
            assert!(v.verify(&c).is_ok());
            assert_eq!((n.pairings(), n.resolver_calls), (0, 0), "{n:?}");
            assert!(matches!(v.verify(&x), Err(Reject::L02Decode(_))));
        "#;
        let got: Vec<String> = assertions(body)
            .iter()
            .map(|(a, _)| classify(a).unwrap())
            .collect();
        assert_eq!(
            got,
            ["L23", "accept", "pairings 0, resolver calls 0", "L02"]
        );
        assert!(classify("something_else()").is_err());
        // A #[cfg] on the line before an assertion selects an instantiation.
        let body = "    #[cfg(feature = \"aggregate-variant\")]\n    assert!(r.is_ok());\n    assert!(q.is_ok());";
        let insts: Vec<Inst> = assertions(body).iter().map(|x| x.1).collect();
        assert_eq!(insts, [Inst::Aggregate, Inst::Both]);
        assert_eq!(
            compress(&["L02".into(), "L02".into(), "L05".into()]),
            "L02 (×2); L05"
        );
    }
}
